### ISSUE TITLE
Add option to toggle immediately

### ISSUE THREAD

**Issue by tjmille2** [Mahfa/DayNightSwitch#1]
Add option to toggle immediately without animation.

**Comment by Mahfa** [comment]
hi there is an method for that in DayNightSwitch class called setIsNight(booelan , boolean)
[link](https://github.com/Mahfa/DayNightSwitch/blob/61a22138d7c0830965a07190ba66b2914991f6a4/lib/src/main/java/com/mahfa/dnswitch/DayNightSwitch.java#L170)
